security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        userprovider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: userprovider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            stateless: true
            guard:
                 authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: userprovider
            json_login:
                check_path: /login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }