#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path:     /register
  controller: App\Controller\SecurityController::register

login:
  path:     /login
  controller: App\Controller\SecurityController::login
  
logout:
  path: /logout